_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
alpha:
    value: 32
alpha_weight:
    value: 0.3
factors:
    value: 64
iterations:
    value: 32
regularization:
    value: 0.7
